server:
  port: ${PORT:8080}

spring:
  application:
    name: FellowshipBackend
  data:
    mongodb:
      auto-index-creation: true

# Aws
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-south-1

aws:
  sqs:
    accessKey: ${ACCESS_KEY}
    secretKey: ${SECRET_KEY}
    queue:
      names:
        notification_queue: notification_queue

# Logging
logging:
  level:
    root: INFO

# Auth
auth:
  login:
    path: /api/v1/login
  register:
    path: /api/v1/user/create

jwt:
  secret: 3795fb81da1c44672f85b274613587acf9fa7435a1f4c7a73daee718a7b629337f7a3a9bece496c7a294fa85c421377eaf8dce6afb91d5ebcd1ea3a4beff948a
  token:
    expiration: 86400000
    secret: 3795fb81da1c44672f85b274613587acf9fa7435a1f4c7a73daee718a7b629337f7a3a9bece496c7a294fa85c421377eaf8dce6afb91d5ebcd1ea3a4beff948a
  refresh:
    token:
      expiration: 129600000
      secret: 3795fb81da1c44672f85b274613587acf9fa7435a1f4c7a73daee718a7b629337f7a3a9bece496c7a294fa85c421377eaf8dce6afb91d5ebcd1ea3a4beff948a

# Custom
skipUrls: /api/v1/login

scholarships:
  page:
    offset: 10
  expiration: 30

mail:
  from: ${SENDER_EMAIL}
  to: ${RECIPIENT_EMAIL}